Repository CodingNomads/course-java-labs-fundamentals, pull requests merged in 2019-02, with the labels that each got.

#35 Integrating part1 Jordan
  src/main/java/com/codingnomads/part_01/Exercise_01.java
  src/main/java/com/codingnomads/part_01/Exercise_02.java
  src/main/java/com/codingnomads/part_01/Exercise_03.java
  src/main/java/com/codingnomads/part_01/Exercise_04.java
  src/main/java/com/codingnomads/part_01/Exercise_05.java
  src/main/java/com/codingnomads/part_01/Exercise_06.java
  src/main/java/com/codingnomads/part_01/Exercise_07.java
  src/main/java/com/codingnomads/part_01/Exercise_08.java
  src/main/java/com/codingnomads/part_01/Exercise_09.java
  src/main/java/com/codingnomads/part_01/Exercise_10.java
  src/main/java/com/codingnomads/part_01/Exercise_11.java
Labels: ready-for-review, ready-to-merge

#37 Cristian_Part1 Integration
  src/main/java/com/codingnomads/part_01/Exercise_01.java
  src/main/java/com/codingnomads/part_01/Exercise_02.java
  src/main/java/com/codingnomads/part_01/Exercise_03.java
  src/main/java/com/codingnomads/part_01/Exercise_04.java
  src/main/java/com/codingnomads/part_01/Exercise_05.java
  src/main/java/com/codingnomads/part_01/Exercise_06.java
  src/main/java/com/codingnomads/part_01/Exercise_07.java
  src/main/java/com/codingnomads/part_01/Exercise_08.java
  src/main/java/com/codingnomads/part_01/Exercise_09.java
  src/main/java/com/codingnomads/part_01/Exercise_10.java
  src/main/java/com/codingnomads/part_01/Exercise_11.java
Labels: ready-for-review, ready-to-merge

#36 Exercises Part1
  src/main/java/com/codingnomads/part_01/Exercise_01.java
  src/main/java/com/codingnomads/part_01/Exercise_02.java
  src/main/java/com/codingnomads/part_01/Exercise_03.java
  src/main/java/com/codingnomads/part_01/Exercise_04.java
  src/main/java/com/codingnomads/part_01/Exercise_05.java
  src/main/java/com/codingnomads/part_01/Exercise_06.java
  src/main/java/com/codingnomads/part_01/Exercise_07.java
  src/main/java/com/codingnomads/part_01/Exercise_08.java
  src/main/java/com/codingnomads/part_01/Exercise_09.java
  src/main/java/com/codingnomads/part_01/Exercise_10.java
  src/main/java/com/codingnomads/part_01/Exercise_11.java
Labels: ready-for-review

#38 Eileen's part 1 exercises
  src/main/java/com/codingnomads/part_01/Exercise_01.java
  src/main/java/com/codingnomads/part_01/Exercise_02.java
  src/main/java/com/codingnomads/part_01/Exercise_03.java
  src/main/java/com/codingnomads/part_01/Exercise_04.java
  src/main/java/com/codingnomads/part_01/Exercise_05.java
  src/main/java/com/codingnomads/part_01/Exercise_06.java
  src/main/java/com/codingnomads/part_01/Exercise_07.java
  src/main/java/com/codingnomads/part_01/Exercise_08.java
  src/main/java/com/codingnomads/part_01/Exercise_09.java
  src/main/java/com/codingnomads/part_01/Exercise_10.java
  src/main/java/com/codingnomads/part_01/Exercise_11.java
Labels: ready-for-review

#40 Cristian part2 Integration
  src/main/java/com/codingnomads/part_02/Exercise_01.java
  src/main/java/com/codingnomads/part_02/Exercise_02.java
  src/main/java/com/codingnomads/part_02/Exercise_03.java
  src/main/java/com/codingnomads/part_02/Exercise_04.java
  src/main/java/com/codingnomads/part_02/Exercise_05.java
  src/main/java/com/codingnomads/part_02/Exercise_06.java
  src/main/java/com/codingnomads/part_02/Exercise_07.java
  src/main/java/com/codingnomads/part_02/Exercise_08.java
  src/main/java/com/codingnomads/part_02/Exercise_09.java
  src/main/java/com/codingnomads/part_02/Exercise_10.java
  src/main/java/com/codingnomads/part_02/Exercise_11.java
  src/main/java/com/codingnomads/part_02/Exercise_12.java
Labels: ready-to-merge

#43 Eileen's part2 exercises
  src/main/java/com/codingnomads/part_02/Exercise_01.java
  src/main/java/com/codingnomads/part_02/Exercise_02.java
  src/main/java/com/codingnomads/part_02/Exercise_03.java
  src/main/java/com/codingnomads/part_02/Exercise_04.java
  src/main/java/com/codingnomads/part_02/Exercise_05.java
  src/main/java/com/codingnomads/part_02/Exercise_06.java
  src/main/java/com/codingnomads/part_02/Exercise_07.java
  src/main/java/com/codingnomads/part_02/Exercise_08.java
  src/main/java/com/codingnomads/part_02/Exercise_09.java
  src/main/java/com/codingnomads/part_02/Exercise_10.java
  src/main/java/com/codingnomads/part_02/Exercise_11.java
  src/main/java/com/codingnomads/part_02/Exercise_12.java
Labels: ready-to-merge

#41 Part2 Exercises Commited
  src/main/java/com/codingnomads/part_02/Exercise_01.java
  src/main/java/com/codingnomads/part_02/Exercise_02.java
  src/main/java/com/codingnomads/part_02/Exercise_03.java
  src/main/java/com/codingnomads/part_02/Exercise_04.java
  src/main/java/com/codingnomads/part_02/Exercise_05.java
  src/main/java/com/codingnomads/part_02/Exercise_06.java
  src/main/java/com/codingnomads/part_02/Exercise_07.java
  src/main/java/com/codingnomads/part_02/Exercise_08.java
  src/main/java/com/codingnomads/part_02/Exercise_09.java
  src/main/java/com/codingnomads/part_02/Exercise_10.java
  src/main/java/com/codingnomads/part_02/Exercise_11.java
  src/main/java/com/codingnomads/part_02/Exercise_12.java
Labels: ready-to-merge

#39 Selenis part1 exercise
  src/main/java/com/codingnomads/part_01/Exercise_01.java
  src/main/java/com/codingnomads/part_01/Exercise_02.java
  src/main/java/com/codingnomads/part_01/Exercise_03.java
  src/main/java/com/codingnomads/part_01/Exercise_04.java
  src/main/java/com/codingnomads/part_01/Exercise_05.java
  src/main/java/com/codingnomads/part_01/Exercise_06.java
  src/main/java/com/codingnomads/part_01/Exercise_07.java
  src/main/java/com/codingnomads/part_01/Exercise_08.java
  src/main/java/com/codingnomads/part_01/Exercise_09.java
  src/main/java/com/codingnomads/part_01/Exercise_10.java
  src/main/java/com/codingnomads/part_01/Exercise_11.java
Labels: ready-for-review

#42 Jordan part2
  src/main/java/com/codingnomads/part_01/Exercise_01.java
  src/main/java/com/codingnomads/part_02/Exercise_01.java
  src/main/java/com/codingnomads/part_02/Exercise_02.java
  src/main/java/com/codingnomads/part_02/Exercise_03.java
  src/main/java/com/codingnomads/part_02/Exercise_04.java
  src/main/java/com/codingnomads/part_02/Exercise_05.java
  src/main/java/com/codingnomads/part_02/Exercise_06.java
  src/main/java/com/codingnomads/part_02/Exercise_07.java
  src/main/java/com/codingnomads/part_02/Exercise_08.java
  src/main/java/com/codingnomads/part_02/Exercise_09.java
  src/main/java/com/codingnomads/part_02/Exercise_10.java
  src/main/java/com/codingnomads/part_02/Exercise_11.java
  src/main/java/com/codingnomads/part_02/Exercise_12.java
Labels: ready-to-merge

#45 Cristian part3 Integration
  src/main/java/com/codingnomads/part_02/Exercise_02.java
  src/main/java/com/codingnomads/part_03/Exercise_01.java
  src/main/java/com/codingnomads/part_03/Exercise_02.java
  src/main/java/com/codingnomads/part_03/Exercise_03.java
  src/main/java/com/codingnomads/part_03/Exercise_04.java
  src/main/java/com/codingnomads/part_03/Exercise_05.java
  src/main/java/com/codingnomads/part_03/Exercise_06.java
Labels: ready-to-merge

#48 Alp Part 3 Commit
  src/main/java/com/codingnomads/part_03/Exercise_01.java
  src/main/java/com/codingnomads/part_03/Exercise_02.java
  src/main/java/com/codingnomads/part_03/Exercise_03.java
  src/main/java/com/codingnomads/part_03/Exercise_04.java
  src/main/java/com/codingnomads/part_03/Exercise_05.java
  src/main/java/com/codingnomads/part_03/Exercise_06.java
Labels: ready-to-merge

#49 Jordan part3
  src/main/java/com/codingnomads/part_03/1_questions
  src/main/java/com/codingnomads/part_03/Exercise_01.java
  src/main/java/com/codingnomads/part_03/Exercise_02.java
  src/main/java/com/codingnomads/part_03/Exercise_03.java
  src/main/java/com/codingnomads/part_03/Exercise_04.java
  src/main/java/com/codingnomads/part_03/Exercise_05.java
  src/main/java/com/codingnomads/part_03/Exercise_06.java
Labels: ready-to-merge

#50 Cristian part4 integration
  src/main/java/com/codingnomads/part_04/1_questions
  src/main/java/com/codingnomads/part_04/Exercise_01.java
  src/main/java/com/codingnomads/part_04/Exercise_02.java
  src/main/java/com/codingnomads/part_04/Exercise_03.java
  src/main/java/com/codingnomads/part_04/Exercise_04.java
  src/main/java/com/codingnomads/part_04/Exercise_05.java
  src/main/java/com/codingnomads/part_04/Exercise_06.java
  src/main/java/com/codingnomads/part_04/Exercise_07.java
Labels: ready-for-review

#51 Alp part4
  src/main/java/com/codingnomads/part_04/Exercise_01.java
  src/main/java/com/codingnomads/part_04/Exercise_02.java
  src/main/java/com/codingnomads/part_04/Exercise_03.java
  src/main/java/com/codingnomads/part_04/Exercise_04.java
  src/main/java/com/codingnomads/part_04/Exercise_05.java
  src/main/java/com/codingnomads/part_04/Exercise_06.java
  src/main/java/com/codingnomads/part_04/Exercise_07.java
Labels: ready-to-merge

#47 Eileen's part3 (Updated - please review!)
  src/main/java/com/codingnomads/part_03/1_questions
  src/main/java/com/codingnomads/part_03/Exercise_01.java
  src/main/java/com/codingnomads/part_03/Exercise_02.java
  src/main/java/com/codingnomads/part_03/Exercise_03.java
  src/main/java/com/codingnomads/part_03/Exercise_04.java
  src/main/java/com/codingnomads/part_03/Exercise_05.java
  src/main/java/com/codingnomads/part_03/Exercise_06.java
Labels: ready-to-merge

#53 Cristian part5 integration
  src/main/java/com/codingnomads/part_05/Exercise_01.java
  src/main/java/com/codingnomads/part_05/Exercise_02.java
  src/main/java/com/codingnomads/part_05/Exercise_03.java
  src/main/java/com/codingnomads/part_05/Exercise_04.java
  src/main/java/com/codingnomads/part_05/Exercise_05.java
  src/main/java/com/codingnomads/part_05/Exercise_07.java
  src/main/java/com/codingnomads/part_05/Exercise_08.java
  src/main/java/com/codingnomads/part_05/Exercise_09.java
Labels: ready-to-merge

#54 alp_part5
  src/main/java/com/codingnomads/part_05/1_questions
  src/main/java/com/codingnomads/part_05/Exercise_01.java
  src/main/java/com/codingnomads/part_05/Exercise_02.java
  src/main/java/com/codingnomads/part_05/Exercise_03.java
  src/main/java/com/codingnomads/part_05/Exercise_04.java
  src/main/java/com/codingnomads/part_05/Exercise_05.java
  src/main/java/com/codingnomads/part_05/Exercise_06.java
  src/main/java/com/codingnomads/part_05/Exercise_07.java
  src/main/java/com/codingnomads/part_05/Exercise_08.java
  src/main/java/com/codingnomads/part_05/Exercise_09.java
  src/main/java/com/codingnomads/part_08/CustomSample.java
  src/main/java/com/codingnomads/part_08/ExceptionHandle.java
  src/main/java/com/codingnomads/part_08/ThrowSample.java
Labels: ready-to-merge

#52 Jordan part4
  src/main/java/com/codingnomads/part_04/Exercise_01.java
  src/main/java/com/codingnomads/part_04/Exercise_02.java
  src/main/java/com/codingnomads/part_04/Exercise_03.java
  src/main/java/com/codingnomads/part_04/Exercise_04.java
  src/main/java/com/codingnomads/part_04/Exercise_05.java
  src/main/java/com/codingnomads/part_04/Exercise_06.java
  src/main/java/com/codingnomads/part_04/Exercise_07.java
Labels: comments-pending

#65 Jordan part5
  src/main/java/com/codingnomads/part_05/1_questions
  src/main/java/com/codingnomads/part_05/Exercise_01.java
  src/main/java/com/codingnomads/part_05/Exercise_02.java
  src/main/java/com/codingnomads/part_05/Exercise_03.java
  src/main/java/com/codingnomads/part_05/Exercise_04.java
  src/main/java/com/codingnomads/part_05/Exercise_05.java
  src/main/java/com/codingnomads/part_05/Exercise_05a.java
  src/main/java/com/codingnomads/part_05/Exercise_07.java
  src/main/java/com/codingnomads/part_05/Exercise_08.java
  src/main/java/com/codingnomads/part_05/Exercise_09.java
Labels: ready-to-merge
